fix(dde-lowpower): missing c++11 cxxflags
fix build error for mips, longxin needs to use gcc5, but lowpower does
not specify c++11, compiling qt fails.

error: #error Qt requires a C++11 compiler and yours does not seem to be
that.

Change-Id: I0ef522dbdeb34c8c7eab5338f3fab112ab52b23b